import Footer from "@/components/common/footer";
import Header from "@/components/common/header";
import type { Metadata } from "next";
import { ToastSetup } from "./toast-setup";

// import Sidebar from '@/components/Sidebar';

export const metadata: Metadata = {
  title: "Her Guardian",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <ToastSetup />
      <Header />
      <div className="flex-1">{children}</div>
      <Footer />
    </>
  );
}
