import Footer from "@/components/common/footer";
import Header from "@/components/common/header";
import type { Metadata } from "next";
import RequireAuth from "@/components/common/RequireAuth";

// import Sidebar from '@/components/Sidebar';

export const metadata: Metadata = {
  title: "Her Guardian",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Header />
      <RequireAuth>
        <div className="flex-1 p-4">{children}</div>
      </RequireAuth>
      <Footer />
    </>
  );
}
